### ISSUE TITLE
Design polishing

### ISSUE THREAD

**Issue by juliusknorr** [nextcloud/text#68]
@jancborchardt To not loose papercuts from #57 and #65, lets keep a list of small design issues here:

## Todo

- [x] Footer is currently hard hidden in the share view. Should be shown on the bottom, but only when you scrolled past the full document. 
- [x] the menu opening delay and sometimes not closing
- [x] the undo/redo should be less opaque than an inactive item when they are not available, that is when there’s nothing more to redo for example (as is the case most times)
- [x] the menu doesn’t seem to reflow if width is changed very quickly (e.g. close the dev tools sidebar which narrowed the window)
- [x] the h1–h6 icons are a bit small, the default label of the heading icon could be "H#" so Markdown ppl know, and also the icon doesn’t seem to reflect in opacity that one of the contents is selected?
- [x] On mobile, cut the "2 minutes ago" indicator, probably to "2m" or something like that 
	__Modifying is not that simple, since moment.js doesnt provide a shortened string for that. It is hidden for now, since the last save status shouldn't be that important anyway, as steps are synced separately from save__
- [x] Menu bar out of place when sidebar is open
